### ISSUE TITLE
Couldn't get the first tutorial to work "Tut 01 Hello Triangle"

### ISSUE THREAD

**Issue by euwern** [paroj/gltut#119]
My environment is window linux subsystem. and I have install freeglut 
"sudo apt-get install freeglut3-dev" and also found a header file for glload  "https://github.com/MaikKlein/glload/tree/master/include/glload" 
I changed a line to locate the hfile in glload 
#include "../../glload/include/glload/gl_3_2_comp.h"
and try to compile it with 
g++ -W tut1.cpp -lGL -lglut -lGLU

but I get the following compiling error:
"""
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
/tmp/cc0SjXSK.o: In function `CreateShader(unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
tut1.cpp:(.text+0x21): undefined reference to `_funcptr_glCreateShader'
tut1.cpp:(.text+0x42): undefined reference to `_funcptr_glShaderSource'
tut1.cpp:(.text+0x5c): undefined reference to `_funcptr_glCompileShader'
tut1.cpp:(.text+0x6a): undefined reference to `_funcptr_glGetShaderiv'
tut1.cpp:(.text+0x8c): undefined reference to `_funcptr_glGetShaderiv'
tut1.cpp:(.text+0xb7): undefined reference to `_funcptr_glGetShaderInfoLog'
/tmp/cc0SjXSK.o: In function `CreateProgram(std::vector<unsigned int, std::allocator<unsigned int> > const&)':
tut1.cpp:(.text+0x17a): undefined reference to `_funcptr_glCreateProgram'
tut1.cpp:(.text+0x1a5): undefined reference to `_funcptr_glAttachShader'
tut1.cpp:(.text+0x1d1): undefined reference to `_funcptr_glLinkProgram'
tut1.cpp:(.text+0x1df): undefined reference to `_funcptr_glGetProgramiv'
tut1.cpp:(.text+0x1fd): undefined reference to `_funcptr_glGetProgramiv'
tut1.cpp:(.text+0x228): undefined reference to `_funcptr_glGetProgramInfoLog'
tut1.cpp:(.text+0x292): undefined reference to `_funcptr_glDetachShader'
/tmp/cc0SjXSK.o: In function `InitializeProgram()':
tut1.cpp:(.text+0x35e): undefined reference to `_funcptr_glDeleteShader'
/tmp/cc0SjXSK.o: In function `InitializeVertexBuffer()':
tut1.cpp:(.text+0x3d8): undefined reference to `_funcptr_glGenBuffers'
tut1.cpp:(.text+0x3eb): undefined reference to `_funcptr_glBindBuffer'
tut1.cpp:(.text+0x401): undefined reference to `_funcptr_glBufferData'
tut1.cpp:(.text+0x41e): undefined reference to `_funcptr_glBindBuffer'
/tmp/cc0SjXSK.o: In function `init()':
tut1.cpp:(.text+0x442): undefined reference to `_funcptr_glGenVertexArrays'
tut1.cpp:(.text+0x455): undefined reference to `_funcptr_glBindVertexArray'
/tmp/cc0SjXSK.o: In function `display()':
tut1.cpp:(.text+0x46d): undefined reference to `_funcptr_glClearColor'
tut1.cpp:(.text+0x486): undefined reference to `_funcptr_glClear'
tut1.cpp:(.text+0x494): undefined reference to `_funcptr_glUseProgram'
tut1.cpp:(.text+0x4a5): undefined reference to `_funcptr_glBindBuffer'
tut1.cpp:(.text+0x4bb): undefined reference to `_funcptr_glEnableVertexAttribArray'
tut1.cpp:(.text+0x4c9): undefined reference to `_funcptr_glVertexAttribPointer'
tut1.cpp:(.text+0x4f2): undefined reference to `_funcptr_glDrawArrays'
tut1.cpp:(.text+0x50a): undefined reference to `_funcptr_glDisableVertexAttribArray'
tut1.cpp:(.text+0x518): undefined reference to `_funcptr_glUseProgram'
/tmp/cc0SjXSK.o: In function `reshape(int, int)':
tut1.cpp:(.text+0x53c): undefined reference to `_funcptr_glViewport'
collect2: error: ld returned 1 exit status

**Comment by paroj** [comment]
fixed with db01d1c5d255a9e819facb9dcfc47cd560b27268
