### ISSUE TITLE
Error building the document pdf

### ISSUE THREAD

**Issue by MaSosa314** [paroj/gltut#126]
Hi. Recently i try to build the pdf of the book. There is an error in the BuildComputerFO.lua script:

![image](https://user-images.githubusercontent.com/48865731/99251999-089a6280-27ed-11eb-8100-69ecc333def4.png)

The open mode should be "w+" instead of "wt".

**Comment by paroj** [comment]
No, I think wt is correct

**Comment by MaSosa314** [comment]
When i tried to execute the script i got the next error:
![image](https://user-images.githubusercontent.com/48865731/99253871-3df47f80-27f0-11eb-95c2-fed05dd883a8.png)

May be i'm doing something wrong. I follow the steps in the [Rebuilding the PDF Documentation](https://github.com/paroj/gltut#rebuilding-the-pdf-documentation)

**Comment by MaSosa314** [comment]
I found that "wt" is used in python, since t refers to "text". You may have gotten confused with python. From the [lua web page](https://www.lua.org/pil/21.2.html) page:

![image](https://user-images.githubusercontent.com/48865731/99254632-6761db00-27f1-11eb-8f02-724bdf8a2be4.png)
