### ISSUE TITLE
The latest release version, glsdk...

### ISSUE THREAD

**Issue by JustMyD** [paroj/gltut#132]
Hi. My situation: don't have internet on pc (only mobile) and I can only download latest release version, but this version doesn't contain glsdk folder... please, update release version, I will be very thankful:)

**Comment by homeisfar** [comment]
Try this: On the main project page click the green "Code" button to open the menu. Underneath the clone URL is an option to download a ZIP of the repository at the latest commit without having to clone it.

**Comment by Skullfurious** [comment]
This helped me as well, thank you. It might be worth making another release with the proper files included. 

Have a great day!

**Comment by paroj** [comment]
0.4.0 released
