### ISSUE TITLE
Build Issue On ArchLinux - Config.h: No such file or directory

### ISSUE THREAD

**Issue by broaken13** [paroj/gltut#147]
.../code/gltut-0.4.0/glsdk/freeglut/src/freeglut_internal.h:32:14: fatal error: config.h: No such file or directory

Get this error after running the build steps in the README

**Comment by isinyaaa** [comment]
@broaken13 `cd` into `glsdk/freeglut` then run

```bash
chmod +x autogen.sh
./autogen.sh
./configure
``` 

now go back to gltut root and try building again :).

**Comment by broaken13** [comment]
Working now. Thank you!
