### ISSUE TITLE
Missing image in Chapter 13

### ISSUE THREAD

**Issue by georgerbr** [paroj/gltut#2]
Figure 13.2 in the [initial page](https://paroj.github.io/gltut/Illumination/Tutorial%2013.html) of Chapter 13 has two images:
- the first is `Illumination/CirclePythagorean.svg`, which is present;
- the second is `Illumination/PythagoreanTheorem.svg`, which is missing.

![ch13_missing_image](https://cloud.githubusercontent.com/assets/4930759/15802258/ca611192-2a82-11e6-86b5-489ce6036843.png)

The missing image is [available](https://bitbucket.org/alfonse/gltut/src/6e01a2fe26998632434a719ae67698f71e298c1f/Documents/Illumination/PythagoreanTheorem.svg?at=default&fileviewer=file-view-default) in Jason McKesson's Bitbucket repository.

**Comment by paroj** [comment]
this is not a missing image, but a formula I missed when converting everything to inline mathml.

this needs to be updated:
https://github.com/paroj/gltut/blob/master/Documents/Illumination/Tutorial%2013.xml#L288
