### ISSUE TITLE
glsdk could not compiled on mac

### ISSUE THREAD

**Issue by paroj** [paroj/gltut#82]
Originally reported by: **xjtudevilknight (Bitbucket: [xjtudevilknight](http://bitbucket.org/xjtudevilknight), GitHub: [xjtudevilknight](http://github.com/xjtudevilknight))**

---

==== Building glload (debug) ====
==== Building glimg (debug) ====
==== Building freeglut (debug) ====
freeglut_callbacks.c
In file included from src/freeglut_callbacks.c:29:
src/freeglut_internal.h:107:14: fatal error: 'GL/glx.h' file not found
# include <GL/glx.h>

```
         ^
```

1 error generated.
make[1]: **\* [obj/Debug/freeglut_callbacks.o] Error 1
make: **\* [freeglut] Error 2

---
- Bitbucket: https://bitbucket.org/alfonse/gltut/issue/113

**Comment by oreqizer** [comment]
Compiling using `CPPFLAGS=-I/opt/X11/include make config=debug` worked for me
